name: Build and push Docker images to GitHub Packages
on: push
jobs:
  cloudflare_dyndns:
    name: Build and push cloudflare-dyndns
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          context: ./
          push: true
          tags: ghcr.io/L480/cloudflare-dyndns:latest
